kind: Pod
apiVersion: v1
metadata:
  name: tolarations1
  labels:
    purpose: "tolarations-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx