kind: Pod
apiVersion: v1
metadata:
  name: node-selector1
  labels:
    purpose: "node-selector-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx